add ctx propagation on all lib functions
CeoFred/fast-otp pull request #4
Opened 2024-01-27 03:27 UTC by neymarjimoh

Enhancing the lib functions to include context for increased user controls would be valuable. This would give the end developer utilizing this library more control from within their applications.

```
payload := fastotp.GenerateOTPPayload{
    Delivery: OtpDelivery{
      "email": "example@example.com",
    },
		Identifier:  "user123",
		TokenLength: 6,
		Type:        "numeric",
		Validity:    120,
	}

// Generate OTP
otp, err := client.GenerateOTP(ctx, payload)
// ... I can cancel or set timeout based on my business rules
```

2024-01-27 10:09 UTC, LordRahl90 requested changes
Great work, 
However, there's no need to expose the values in the `APIClient`.

2024-01-27 10:09 UTC, LordRahl90 commented on lib/http.go
> +		Ctx:     ctx,
there's no point exporting these values, as you don't want them changed/accessed directly anyways

2024-01-27 18:05 UTC, neymarjimoh commented
> Great work, However, there's no need to expose the values in the `APIClient`.

Thanks for the feedback. I agree that exposing `BaseURL` and `APIKey` directly may not be ideal. I just added the Ctx key for managing user's context that's why and noticed your PR handled that. Will modify now

2024-01-27 20:15 UTC, CeoFred requested changes

2024-01-27 20:15 UTC, CeoFred commented on go.mod
> +go 1.23
Go version is `1.21.2` work with that.

2024-01-27 21:52 UTC, LordRahl90 approved these changes

2024-01-27 21:58 UTC, LordRahl90 commented
> > Great work, However, there's no need to expose the values in the `APIClient`.
> 
> Thanks for the feedback. I agree that exposing `BaseURL` and `APIKey` directly may not be ideal. I just added the Ctx key for managing user's context that's why and noticed your PR handled that. Will modify now

Great work boss 🙇‍♂️

2024-01-28 04:22 UTC, neymarjimoh commented
> > > Great work, However, there's no need to expose the values in the `APIClient`.
> > 
> > 
> > Thanks for the feedback. I agree that exposing `BaseURL` and `APIKey` directly may not be ideal. I just added the Ctx key for managing user's context that's why and noticed your PR handled that. Will modify now
> 
> Great work boss 🙇‍♂️

Thanks boss

2024-01-28 19:01 UTC, merged